---
abstract: 'Specification for setup module'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Setup
requires:
  Rinci: v1.1.23
resources:
  homepage: http://search.cpan.org/dist/Setup/
  repository: http://github.com/sharyanto/perl-Setup
version: 1.0.3
